name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install dependencies
        run: nix develop --command make install

      - name: Run Ruff linter
        run: nix develop --command make lint

      - name: Check code formatting
        run: nix develop --command make format-check

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install dependencies
        run: nix develop --command make install

      - name: Run mypy
        run: nix develop --command make type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install dependencies
        run: nix develop --command make install

      - name: Run tests
        run: nix develop --command make test-cov

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          use_oidc: true
          files: ./junit.xml
          fail_ci_if_error: false
          verbose: true
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./coverage.xml
          fail_ci_if_error: false
        continue-on-error: true

  all-checks:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [lint-and-format, type-check, test]
    if: always()
    steps:
      - name: Check if all jobs succeeded
        run: |
          if [[ "${{ needs.lint-and-format.result }}" != "success" ]]; then
            echo "Lint and format check failed"
            exit 1
          fi
          if [[ "${{ needs.type-check.result }}" != "success" ]]; then
            echo "Type check failed"
            exit 1
          fi
          if [[ "${{ needs.test.result }}" != "success" ]]; then
            echo "Tests failed"
            exit 1
          fi
          echo "All checks passed!"
